# 로그 레벨
logging:
  level:
    kr.co.seculink: debug

# spring profile
spring:
  config:
    activate:
      on-profile: local, default
  datasource:
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.110.175:1521:HBBL
      username: PANDA
      password: PANDA
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false

server:
  port: 8089

jwt:
  token:
    header: Authorization
    role: USER
    issuer: hubble-local
    clientId: untactor-server
    expirySeconds: 31536000

upload:
  prof: C:\\project\\workspace\\wms\\src\\main\\resources\\static\\uploads\\
  event: C:\\project\\workspace\\wms\\src\\main\\resources\\static\\uploads\\
  temp: C:\\project\\workspace\\wms\\src\\main\\resources\\static\\uploads\\temp\\
  hwork: C:\\project\\workspace\\wms\\src\\main\\resources\\static\\uploads\\
